version: '3'
services:
  dev:
    image: lensesio/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1
    ports:
      - "2181:2181"
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "3030:3030"
    volumes:
      - ./target:/connectors/batch-sink-connector
