name: Create JAR and Sandbox Image
on:
  push:
    branches: [master]
jobs:
  create and publish jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v1
        with:
          name: jar
          path: target/*connector.jar
          
  create and push sandbox image: 
    runs-on: ubuntu-latest
    needs: create and publish jar
    steps:
      - name: Download connector JAR from actions
        uses: actions/download-artifact@v1
        with:
          name: jar  
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          image_name: ${GITHUB_SHA::8},latest
